### ISSUE TITLE
GC not working?

### ISSUE THREAD

**Issue by wboeke** [shixiongfei/ape#1]
Is it possible that the GC does'nt work?
I compiled ape as follows:
   gcc *.c -o ape -lm
It appears that the following recursive function
```
(defn fib (n)
  (if (< n 2) 1 (+ (fib (- n 1)) (fib (- n 2)))
  ))
```
makes the program crash if e.g. (fib 20) is tried

**Comment by shixiongfei** [comment]
Can you give me more information?
I tested `gcc *.c -o ape -lm` on my MacBook and it worked fine.

**Comment by shixiongfei** [comment]
@wboeke I made some fixes to possible crashes, You can try the latest version again.

**Comment by wboeke** [comment]
I am sorry, I replied to you by mail, however: that does not work, apparently. Anyhow, the problem is solved. Thanks!

**Comment by shixiongfei** [comment]
I didn't get any mail. Thank you for your feedback and glad you like it.
